# Default values for tweeviz.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: mirantisworkloads/
  name: tweeviz
  tag: 1.1.0
  pullPolicy: IfNotPresent

port: 8589
minPopularity: 1
topListSize: 25
storage: "hdfs" # cassandra or hdfs

# Set custom header to be displayed in viz page
header: "Twitter Stats"

probeInitialDelaySeconds: 10
probePeriodSeconds: 5

service:
  type: NodePort # or ClusterIP or LoadBalancer

  nodePort: ""

  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  annotations: {}

ingress:
  enabled: false
  hosts: []
    #- some.domain
  tls:
    enabled: false
    secretName: ""
  annotations: {}
    #kubernetes.io/ingress.class: nginx

resources:
  #requests:
  #  cpu: 100m
  #  memory: 512Mi
  #limits:
  #  cpu: 100m
  #  memory: 512Mi

hdfs:
  # if disabled, subchart will not be deployed
  deployChart: false
  path: /

  # these values should be set if subchart deployment is disabled:
  addresses:
    namenode: ""

cassandra:
  deployChart: false
  addresses:
    cassandra: ""
  keyspace: mirantis
  table: tweetics

istio:
  enabled: false
