package visualization

import (
	"bytes"
	"fmt"
	"github.com/Aptomi/aptomi/pkg/util"
	"github.com/awalterschulze/gographviz"
	"image"
	"image/png"
	"os"
	"os/exec"
)

// CreateImage draws graphviz graph and returns it as an image
func CreateImage(graph *gographviz.Graph) (image.Image, error) { // nolint: interfacer
	graphStr := graph.String()

	// Original graph in .dot
	fileNameDot := util.WriteTempFile("graphviz", graphStr)
	defer os.Remove(fileNameDot) // nolint: errcheck

	// Graph with improved layout in .dot
	fileNameDotFlat := fileNameDot + ".flat.dot"
	defer os.Remove(fileNameDotFlat) // nolint: errcheck

	// Graph in .png
	fileNamePng := fileNameDot + ".png"
	defer os.Remove(fileNamePng) // nolint: errcheck

	// Call graphviz to unflatten an image and get a better layout
	{
		cmd := "unflatten"
		args := []string{"-f", "-l", "4", "-o" + fileNameDotFlat, fileNameDot}
		command := exec.Command(cmd, args...)
		var outBuf, errBuf bytes.Buffer
		command.Stdout = &outBuf
		command.Stderr = &errBuf
		if err := command.Run(); err != nil || len(errBuf.String()) > 0 {
			unableToExecute(cmd, args, outBuf, errBuf, err, graphStr)
		}
	}

	// Call graphviz to generate an image
	{
		cmd := "dot"
		args := []string{"-Tpng", "-o" + fileNamePng, fileNameDotFlat}
		// args := []string{"-Tpng", "-Kfdp", "-o" + fileNamePng, fileNameDotFlat}
		command := exec.Command(cmd, args...)
		var outBuf, errBuf bytes.Buffer
		command.Stdout = &outBuf
		command.Stderr = &errBuf
		if err := command.Run(); err != nil || len(errBuf.String()) > 0 {
			unableToExecute(cmd, args, outBuf, errBuf, err, graphStr)
		}
	}

	// Read image and return
	filePng, err := os.Open(fileNamePng)
	if err != nil {
		panic(fmt.Sprintf("Unable to load PNG generated by graphviz '%s': %s", fileNamePng, err))
	}
	defer filePng.Close() // nolint: errcheck
	return png.Decode(filePng)
}

func unableToExecute(cmd string, args []string, outb bytes.Buffer, errb bytes.Buffer, err error, graph string) {
	panic(fmt.Sprintf("Unable to execute graphviz '%s' with '%s': %s %s %s\n%s", cmd, args, outb.String(), errb.String(), err, graph))
}
