// Package component defines all component-specific actions, which get generated by the policy diff when component
// changes occur for specific component instances. Component-specific action is supposed to handle a certain change
// for a given component instance (e.g. create, update, delete, attach dependency, remove dependency, etc).
package component
